import React, { createContext, useContext, useState, useEffect } from 'react'

const AppContext = createContext(null)

export const TRANSLATIONS = {
  vi: {
    appName: 'Consensus Doctor',
    tagline: 'Nền tảng AI Y tế · Digital Twin Bệnh nhân',
    login: 'Đăng nhập',
    register: 'Đăng ký',
    logout: 'Đăng xuất',
    email: 'Email',
    password: 'Mật khẩu',
    name: 'Họ và tên',
    continueGoogle: 'Tiếp tục với Google',
    continueApple: 'Tiếp tục với Apple',
    orEmail: 'Hoặc dùng email',
    noAccount: 'Chưa có tài khoản?',
    hasAccount: 'Đã có tài khoản?',
    welcome: 'Xin chào',
    dashboard: 'Tổng quan',
    patients: 'Bệnh nhân',
    imaging: 'Chẩn đoán hình ảnh',
    checkin: 'Kiểm tra triệu chứng',
    matrix3dBody: 'Matrix-3D Body',
    omnidirectional3dBody: 'Omnidirectional Explorable 3D Body Generation',
    twin: 'Digital Twin',
    telemedicine: 'Telemedicine',
    statAnalysis: 'AI Agent phân tích thống kê',
    simulation: 'Mô phỏng điều trị',
    consensus: 'Đồng thuận AI',
    protein3d: 'Protein 3D',
    swarmCouncil: '🏛 Hội đồng AI',
    adminPanel: 'Quản trị hệ thống',
    familyTree: 'Gia phả bệnh lý',
    familyRelationship: 'Family Medical Relationship',
    uploadRecords: 'Tải lên hồ sơ',
    patientRecord: 'Hồ sơ bệnh nhân',
    addPatient: 'Thêm bệnh nhân',
    allPatients: 'Tất cả bệnh nhân',
    medicalHistory: 'Lịch sử bệnh án',
    recommendations: 'Gợi ý xét nghiệm',
    darkMode: 'Chế độ tối',
    lightMode: 'Chế độ sáng',
    language: 'Ngôn ngữ',
    profile: 'Hồ sơ cá nhân',
    agentsActive: 'AGENT ĐANG HOẠT ĐỘNG',
    next: 'Tiếp theo',
    back: 'Quay lại',
    save: 'Lưu',
    cancel: 'Hủy',
    upload: 'Tải lên',
    uploadFile: 'Chọn hoặc kéo thả file',
    uploadTypes: 'Hỗ trợ: DICOM, PDF, JPEG, PNG, DOCX',
    familyRelation: 'Quan hệ',
    addFamilyMember: 'Thêm thành viên',
    aiSuggestion: 'Gợi ý AI',
    testSuggestion: 'Xét nghiệm được gợi ý',
    confidence: 'Độ tin cậy',
    allUsers: 'Tất cả người dùng',
    allRecords: 'Tất cả hồ sơ',
    activityLog: 'Nhật ký hoạt động',
    adminOnly: 'Chỉ dành cho quản trị viên',
    loginRequired: 'Vui lòng đăng nhập để tiếp tục',
    patientProgress: 'Tiến triển bệnh',
    uploadSuccess: 'Tải lên thành công',
    relation_self: 'Bệnh nhân',
    relation_father: 'Cha',
    relation_mother: 'Mẹ',
    relation_sibling: 'Anh/Chị/Em',
    relation_child: 'Con',
    relation_spouse: 'Vợ/Chồng',
    relation_grandparent: 'Ông/Bà',
    relation_grandchild: 'Cháu',
    relation_uncle_aunt: 'Chú/Cô',
    relation_cousin: 'Anh em họ',
    // Checkin
    checkinTitle: 'Kiểm tra triệu chứng & Tiền sử',
    seedCollection: 'THU THẬP DỮ LIỆU',
    personalHistory: 'Tiền sử cá nhân',
    familyHistory: 'Tiền sử gia đình',
    currentSymptoms: 'Triệu chứng hiện tại',
    envSignals: 'Tín hiệu môi trường',
    buildTwin: 'Xây dựng Digital Twin →',
    // Imaging
    imagingTitle: 'Phân tích hình ảnh y tế',
    lesionTracking: 'Theo dõi tổn thương',
    aiFinding: 'Phát hiện AI',
    scanTimeline: 'Lịch sử chụp',
    continueCheckin: 'Tiếp tục kiểm tra triệu chứng →',
    // Twin
    twinTitle: 'Digital Twin Y tế',
    twinActive: 'TWIN ĐANG HOẠT ĐỘNG',
    activeAgents: 'Agent đang hoạt động',
    twinFidelity: 'Độ chính xác twin',
    interactionsPerSec: 'Tương tác / giây',
    realityMatch: 'Điểm khớp thực tế',
    bodyComposition: 'Chỉ số cơ thể',
    runSimulation: 'Chạy mô phỏng điều trị →',
    // Telemedicine
    telemedicineTitle: 'Telemedicine · Livestream hội chẩn',
    telemedicineSubtitle: 'Livestream đồng thời 3 bác sĩ vật lý thật và 5 bác sĩ AI agent. Bác sĩ hoặc agent nào không có tín hiệu sẽ tự động hiển thị chế độ OFFLINE.',
    aiAgentRoom: 'Phòng bác sĩ AI agent',
    aiAgentRoomHint: '4 agent online · 1 agent offline standby',
    handoffTitle: 'Luồng hội chẩn song song',
    handoffCopy: 'Video từ bác sĩ thật được ghép với phân tích của AI agent theo thời gian thực, giúp hội đồng Digital Twin chuyển ca sang đồng thuận AI khi đủ dữ liệu.',
    continueAiCouncil: 'Tiếp tục tới Hội đồng AI →',
    // Statistical analysis
    statAnalysisTitle: 'AI Agent phân tích thống kê HPV',
    statAnalysisSubtitle: 'Agent đọc dữ liệu từ bài báo Long Châu, chuẩn hoá các con số thực tế và tạo biểu đồ scatter HTML tương tác với trục Y là tín hiệu HPV (0–100).',
    statFiltersTitle: '4 bộ lọc khám phá',
    statFiltersHint: 'Chọn từng lớp dữ liệu để xem cụm tuổi và tín hiệu HPV mô phỏng.',
    statOutcomeTitle: 'OUTPUT / OUTCOME',
    statOutcomeCopy: 'Biểu đồ mới chuyển ngữ cảnh từ liều thuốc sang tín hiệu HPV, giúp nhận diện nhóm cần tầm soát, chủng nguy cơ cao và tác động của vắc xin.',
    // Simulation
    simulationTitle: 'Mô phỏng điều trị',
    simulationMode: 'CHẾ ĐỘ MÔ PHỎNG',
    selectScenario: 'Chọn kịch bản điều trị',
    projectionHorizon: 'Khoảng chiếu',
    treatmentRoadmap: 'Lộ trình điều trị',
    submitConsensus: 'Gửi tới Đồng thuận AI →',
    // Consensus
    consensusTitle: 'Đồng thuận Agent',
    consensusReached: 'ĐÃ ĐẠT ĐỒNG THUẬN',
    fusionMethod: 'Phương pháp tổng hợp',
    runConsensus: 'Chạy đồng thuận agent',
    newScan: '← Quét mới',
    rerunConsensus: '↺ Chạy lại đồng thuận',
    compareAllMethods: 'So sánh 4 phương pháp tổng hợp',
    // Upload
    uploading: 'Đang tải lên...',
    notes: 'Ghi chú',
    notesPlaceholder: 'Ghi chú (tuỳ chọn)...',
    recordsUploaded: 'hồ sơ đã tải',
    uploadPatientName: 'Bệnh nhân Upload',
    pendingAnalysis: 'Đang chờ phân tích',
    uploadedSummary: 'Tổng cộng {count} hồ sơ được tải lên',
    uploadedTimelineEvent: 'Upload {type}: {label}',
    noUploadPatientName: 'Chưa có hồ sơ upload',
    noUploadPatientDisease: 'Upload hồ sơ để tạo bệnh án cá nhân',
    uploadDataBanner: 'Dữ liệu từ Hồ Sơ Upload',
    uploadDataStats: '{files} file · {images} ảnh có AI phân tích',
    backToDemo: '← Demo Patient',
    backToMyRecords: '← Hồ sơ của tôi',
    backToDemoRecord: '← Quay lại Demo',
    // Admin
    totalUsers: 'Tổng người dùng',
    medicalRecords: 'Hồ sơ y tế',
    analysesToday: 'Phân tích hôm nay',
    activePatients: 'Bệnh nhân đang theo dõi',
    session: 'Phiên làm việc',
    accounts: 'tài khoản',
    records: 'hồ sơ',
    noUsers: 'Chưa có người dùng nào ngoài admin',
    noRecords: 'Chưa có hồ sơ nào được tải lên',
    // Family
    familyTreeTitle: 'Gia phả bệnh lý',
    familyRelationshipTitle: 'Family Medical Relationship',
    membersCount: 'thành viên',
    aiHereditary: 'Phân tích nguy cơ di truyền AI',
    memberList: 'Danh sách thành viên',
    addMember: 'Thêm thành viên',
    confirmDelete: 'Xác nhận xoá?',
    screeningRec: 'Khuyến nghị tầm soát',
    riskHigh: 'Nguy cơ cao',
    riskMedium: 'Nguy cơ trung bình',
    riskLow: 'Nguy cơ thấp',
    fromFamily: 'Từ Gia phả',
    viewingMember: 'Đang xem hồ sơ thành viên gia đình',
    backToMain: '← Quay lại Lê Xuân Khánh',
    // Profile modal
    welcomeTitle: 'Chào mừng đến Consensus Doctor!',
    profileCreated: 'Hồ sơ đã được tạo từ tài khoản của bạn. Xem lại và chỉnh sửa nếu cần.',
    specialtyRole: 'Chuyên khoa / Vai trò',
    optional: 'tùy chọn',
    phone: 'Số điện thoại',
    editAnytime: 'Bạn có thể chỉnh sửa thông tin này bất cứ lúc nào trong phần Hồ sơ cá nhân.',
    skip: 'Bỏ qua',
    saveProfile: '💾 Lưu hồ sơ',
    adminLoginGoogle: 'Đăng nhập Admin (Google)',
    autoAvatar: '· Avatar tự động',
  },
  en: {
    appName: 'Consensus Doctor',
    tagline: 'Medical AI Platform · Patient Digital Twin',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    email: 'Email',
    password: 'Password',
    name: 'Full Name',
    continueGoogle: 'Continue with Google',
    continueApple: 'Continue with Apple',
    orEmail: 'Or use email',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    welcome: 'Welcome',
    dashboard: 'Dashboard',
    patients: 'Patients',
    imaging: 'Imaging Analysis',
    checkin: 'Symptom Check-in',
    matrix3dBody: 'Matrix-3D Body',
    omnidirectional3dBody: 'Omnidirectional Explorable 3D Body Generation',
    twin: 'Digital Twin',
    telemedicine: 'Telemedicine',
    statAnalysis: 'AI Agent Stats',
    simulation: 'Treatment Simulation',
    consensus: 'AI Consensus',
    protein3d: 'Protein 3D',
    swarmCouncil: '🏛 AI Board',
    adminPanel: 'Admin Panel',
    familyTree: 'Family Medical Tree',
    familyRelationship: 'Family Medical Relationship',
    uploadRecords: 'Upload Records',
    patientRecord: 'Patient Record',
    addPatient: 'Add Patient',
    allPatients: 'All Patients',
    medicalHistory: 'Medical History',
    recommendations: 'Test Recommendations',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    language: 'Language',
    profile: 'Profile',
    agentsActive: 'AGENTS ACTIVE',
    next: 'Next',
    back: 'Back',
    save: 'Save',
    cancel: 'Cancel',
    upload: 'Upload',
    uploadFile: 'Select or drag & drop file',
    uploadTypes: 'Supported: DICOM, PDF, JPEG, PNG, DOCX',
    familyRelation: 'Relation',
    addFamilyMember: 'Add Member',
    aiSuggestion: 'AI Suggestion',
    testSuggestion: 'Suggested Tests',
    confidence: 'Confidence',
    allUsers: 'All Users',
    allRecords: 'All Records',
    activityLog: 'Activity Log',
    adminOnly: 'Admin Access Only',
    loginRequired: 'Please login to continue',
    patientProgress: 'Disease Progress',
    uploadSuccess: 'Upload Successful',
    relation_self: 'Patient',
    relation_father: 'Father',
    relation_mother: 'Mother',
    relation_sibling: 'Sibling',
    relation_child: 'Child',
    relation_spouse: 'Spouse',
    relation_grandparent: 'Grandparent',
    relation_grandchild: 'Grandchild',
    relation_uncle_aunt: 'Uncle/Aunt',
    relation_cousin: 'Cousin',
    // Checkin
    checkinTitle: 'Symptom & History Check-in',
    seedCollection: 'SEED COLLECTION',
    personalHistory: 'Personal History',
    familyHistory: 'Family Medical History',
    currentSymptoms: 'Current Symptoms',
    envSignals: 'Environmental Seed Signals',
    buildTwin: 'Build Digital Twin →',
    // Imaging
    imagingTitle: 'Medical Imaging Analysis',
    lesionTracking: 'Lesion Tracking',
    aiFinding: 'AI Finding',
    scanTimeline: 'Scan Timeline',
    continueCheckin: 'Continue to Symptom Check-in →',
    // Twin
    twinTitle: 'Medical Digital Twin',
    twinActive: 'TWIN ACTIVE',
    activeAgents: 'Active agents',
    twinFidelity: 'Twin fidelity',
    interactionsPerSec: 'Interactions / sec',
    realityMatch: 'Reality match score',
    bodyComposition: 'Body Composition Index',
    runSimulation: 'Run Treatment Simulations →',
    // Telemedicine
    telemedicineTitle: 'Telemedicine · Live consultation',
    telemedicineSubtitle: 'A simultaneous livestream with 3 real physical doctors and 5 AI doctor agents. Any doctor or agent without signal is automatically shown in OFFLINE mode.',
    aiAgentRoom: 'AI doctor agent room',
    aiAgentRoomHint: '4 agents online · 1 agent offline standby',
    handoffTitle: 'Parallel consultation flow',
    handoffCopy: 'Real-doctor video is paired with real-time AI agent reasoning so the Digital Twin council can hand off to AI consensus when enough context is available.',
    continueAiCouncil: 'Continue to AI Board →',
    // Statistical analysis
    statAnalysisTitle: 'AI Agent HPV statistical analysis',
    statAnalysisSubtitle: 'The agent reads Long Châu article signals, normalizes the real-world figures, and renders an interactive HTML scatter chart with the Y-axis as HPV signal (0–100).',
    statFiltersTitle: '4 exploration filters',
    statFiltersHint: 'Select each data layer to inspect age clusters and simulated HPV signal.',
    statOutcomeTitle: 'OUTPUT / OUTCOME',
    statOutcomeCopy: 'The new chart shifts the context from dosage to HPV signal, making screening gaps, high-risk strains, and vaccination impact easier to see.',
    // Simulation
    simulationTitle: 'Treatment Simulation',
    simulationMode: 'SIMULATION MODE',
    selectScenario: 'Select Treatment Scenario',
    projectionHorizon: 'Projection horizon',
    treatmentRoadmap: 'Treatment Roadmap',
    submitConsensus: 'Submit to Agent Consensus →',
    // Consensus
    consensusTitle: 'Agent Consensus',
    consensusReached: 'CONSENSUS REACHED',
    fusionMethod: 'Fusion method',
    runConsensus: 'Run Agent Consensus',
    newScan: '← New Scan',
    rerunConsensus: '↺ Re-run Consensus',
    compareAllMethods: 'Compare all 4 fusion methods',
    // Upload
    uploading: 'Uploading...',
    notes: 'Notes',
    notesPlaceholder: 'Notes (optional)...',
    recordsUploaded: 'records uploaded',
    uploadPatientName: 'Upload Patient',
    pendingAnalysis: 'Pending analysis',
    uploadedSummary: '{count} records uploaded in total',
    uploadedTimelineEvent: 'Uploaded {type}: {label}',
    noUploadPatientName: 'No uploaded records yet',
    noUploadPatientDisease: 'Upload records to create your personal medical chart',
    uploadDataBanner: 'Data from Uploaded Records',
    uploadDataStats: '{files} file(s) · {images} AI-analyzed image(s)',
    backToDemo: '← Demo Patient',
    backToMyRecords: '← My records',
    backToDemoRecord: '← Back to Demo',
    // Admin
    totalUsers: 'Total Users',
    medicalRecords: 'Medical Records',
    analysesToday: 'Analyses Today',
    activePatients: 'Active Patients',
    session: 'Session',
    accounts: 'accounts',
    records: 'records',
    noUsers: 'No users yet except admin',
    noRecords: 'No records uploaded yet',
    // Family
    familyTreeTitle: 'Family Disease Tree',
    familyRelationshipTitle: 'Family Medical Relationship',
    membersCount: 'members',
    aiHereditary: 'AI Hereditary Risk Analysis',
    memberList: 'Member List',
    addMember: 'Add Member',
    confirmDelete: 'Confirm Delete?',
    screeningRec: 'Screening Recommendations',
    riskHigh: 'High Risk',
    riskMedium: 'Medium Risk',
    riskLow: 'Low Risk',
    fromFamily: 'From Family Tree',
    viewingMember: 'Viewing family member record',
    backToMain: '← Back to Lê Xuân Khánh',
    // Profile modal
    welcomeTitle: 'Welcome to Consensus Doctor!',
    profileCreated: 'Your profile was created from your account. Review and update if needed.',
    specialtyRole: 'Specialty / Role',
    optional: 'optional',
    phone: 'Phone',
    editAnytime: 'You can edit this information anytime in your Profile settings.',
    skip: 'Skip',
    saveProfile: '💾 Save profile',
    adminLoginGoogle: 'Admin login (Google)',
    autoAvatar: '· Auto avatar',
  }
}

export function AppProvider({ children }) {
  const [theme, setTheme] = useState(() => localStorage.getItem('cdoc_theme') || 'dark')
  const [lang, setLang] = useState(() => localStorage.getItem('cdoc_lang') || 'vi')

  useEffect(() => {
    localStorage.setItem('cdoc_theme', theme)
    document.documentElement.setAttribute('data-theme', theme)
  }, [theme])

  useEffect(() => {
    localStorage.setItem('cdoc_lang', lang)
  }, [lang])

  const t = (key) => TRANSLATIONS[lang]?.[key] || TRANSLATIONS['vi'][key] || key

  const toggleTheme = () => setTheme(t => t === 'dark' ? 'light' : 'dark')

  return (
    <AppContext.Provider value={{ theme, toggleTheme, lang, setLang, t }}>
      {children}
    </AppContext.Provider>
  )
}

export const useApp = () => useContext(AppContext)
